services:
  traefik:
    image: traefik:v3.0  
    ports:
      - "80:80"           
      - "9090:8080"       #traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - traefik-net      

  frontend:
    build: 
      context: ./frontend-vue
      dockerfile: Dockerfile
      args:
        - VUE_APP_BACKEND_HOSTNAME=backend.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    # ports: 
    #   - 8880:8180
    depends_on:
      - backend
      - redis
    networks:
      - traefik-net

  backend:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    environment:
      - REDISSERVER_hostname=redis
      - EHRBASESERVER_hostname=host.docker.internal
    # ports:
    #   - 5000:5000
    depends_on:
      - redis     
    networks:
      - traefik-net         

  redis:
    image: redis:7-alpine
    command:  redis-server  /redis/redis.conf
    # ports:
    # - 6379:6379
    volumes:
    - ./redis:/redis
    networks:
      - traefik-net

  ehrbase:
    image: ${EHRBASE_IMAGE:-ehrbase/ehrbase:2.15.0}
    env_file:
      - .env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
    links:
      - ehrdb
        #      - keycloak
    depends_on:
      ehrdb:
        condition: service_healthy
        #    keycloak:
        #        condition: service_started
    # ports:
    #   - "8080:8080"
    networks:
      - traefik-net

  ehrdb:
    image: ${EHRBASE_POSTGRES_IMAGE:-ehrbase/ehrbase-v2-postgres:16.2}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
    # ports:
    #   - "5432:5432"
    networks:
      - traefik-net
    volumes:
      - ./.pgdata:/var/lib/postgresql/data    


networks:
  traefik-net:
    driver: bridge
